---

- hosts: all
  become: true
  tasks:

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform 
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.13.4/terraform_1.13.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

